# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 01:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_remove_entries_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2017, 12, 21, 1, 39, 55, 118593, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
