# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_remove_entries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='content',
            field=models.CharField(max_length=700),
        ),
    ]
