# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20171220_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='content',
            field=models.TextField(max_length=700),
        ),
    ]
